[package]
name = "rock_paper_scissors"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { git = "https://github.com/raylib-rs/raylib-rs.git" }
ecs = { git = "https://github.com/jurmc/ecs.git" }
